"""add_users_user_sessions_refactor_candidates_admins

Revision ID: 0ac80b149312
Revises: e3a9ca9bb06e
Create Date: 2026-03-22 18:33:39.451886

"""
from typing import Sequence, Union
import uuid as _uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '0ac80b149312'
down_revision: Union[str, Sequence[str], None] = 'e3a9ca9bb06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create new tables
    op.create_table(
        'users',
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('CANDIDATE', 'ADMIN', name='user_role'), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'admins',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_admins_user_id'),
    )
    op.create_table(
        'user_sessions',
        sa.Column('token', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('token'),
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)

    # 2. Add user_id to candidates as nullable first (so existing rows don't violate NOT NULL)
    op.add_column('candidates', sa.Column('user_id', sa.UUID(), nullable=True))

    # 3. Data migration: create a User row for every existing candidate, then populate user_id
    conn = op.get_bind()
    candidates = conn.execute(
        sa.text("SELECT id, email, full_name, created_at FROM candidates")
    ).fetchall()
    for row in candidates:
        new_user_id = _uuid.uuid4()
        email = row.email or f"unknown+{row.id}@placeholder.invalid"
        full_name = row.full_name or "Unknown"
        conn.execute(
            sa.text(
                "INSERT INTO users (id, email, full_name, role, created_at, updated_at) "
                "VALUES (:id, :email, :full_name, 'CANDIDATE', :created_at, now())"
            ),
            {"id": new_user_id, "email": email, "full_name": full_name, "created_at": row.created_at},
        )
        conn.execute(
            sa.text("UPDATE candidates SET user_id = :user_id WHERE id = :id"),
            {"user_id": new_user_id, "id": row.id},
        )

    # 4. Now make user_id NOT NULL and add constraints
    op.alter_column('candidates', 'user_id', nullable=False)
    op.drop_constraint('candidates_email_key', 'candidates', type_='unique')
    op.create_unique_constraint('uq_candidates_user_id', 'candidates', ['user_id'])
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # 5. Drop the columns that moved to users
    op.drop_column('candidates', 'email')
    op.drop_column('candidates', 'full_name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint('uq_candidates_user_id', 'candidates', type_='unique')
    op.create_unique_constraint(op.f('candidates_email_key'), 'candidates', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('candidates', 'user_id')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
