"""add cv_drafts and essay_drafts source

Revision ID: 612f2f64246a
Revises: dd84a02d52ef
Create Date: 2026-04-21 10:46:07.862315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '612f2f64246a'
down_revision: Union[str, Sequence[str], None] = 'dd84a02d52ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_drafts',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'archived')", name='ck_cv_drafts_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cv_drafts_candidate_id', 'cv_drafts', ['candidate_id'], unique=False)
    op.add_column('essay_drafts', sa.Column('source', sa.String(length=20), server_default=sa.text("'human'"), nullable=False))
    op.create_check_constraint(
        "ck_essay_drafts_source",
        "essay_drafts",
        "source IN ('agent', 'human')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_essay_drafts_source", "essay_drafts", type_="check")
    op.drop_column('essay_drafts', 'source')
    op.drop_index('ix_cv_drafts_candidate_id', table_name='cv_drafts')
    op.drop_table('cv_drafts')
    # ### end Alembic commands ###
