"""task_002_initial_persistence

Revision ID: 88dbb33a806a
Revises: 
Create Date: 2026-03-19 22:20:24.352789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88dbb33a806a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'AI', name='audit_actor_type'), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('candidates',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('program_type', sa.Enum('UNDERGRAD', 'GRAD', 'MBA', 'PHD', 'OTHER', name='program_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'PROSPECT', name='candidate_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_candidates_program_type', 'candidates', ['program_type'], unique=False)
    op.create_index('ix_candidates_status', 'candidates', ['status'], unique=False)
    op.create_table('ai_runs',
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.Enum('CLASSIFICATION', 'EXTRACTION', 'GENERATION', 'REVIEW', 'OTHER', name='ai_run_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='ai_run_status'), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_candidate_id', 'ai_runs', ['candidate_id'], unique=False)
    op.create_index('ix_ai_runs_run_type', 'ai_runs', ['run_type'], unique=False)
    op.create_index('ix_ai_runs_status', 'ai_runs', ['status'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', name='uq_candidate_profiles_candidate_id')
    )
    op.create_table('chat_threads',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='chat_thread_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_threads_candidate_id', 'chat_threads', ['candidate_id'], unique=False)
    op.create_table('essay_drafts',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ARCHIVED', name='essay_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_essay_drafts_candidate_id', 'essay_drafts', ['candidate_id'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.Enum('SCHOOL_SELECTION', 'TIMELINE', 'NARRATIVE', 'ESSAY_PLAN', 'OTHER', name='strategy_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', name='strategy_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_decisions_candidate_id', 'strategy_decisions', ['candidate_id'], unique=False)
    op.create_index('ix_strategy_decisions_type', 'strategy_decisions', ['strategy_type'], unique=False)
    op.create_table('task_items',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_items_candidate_id', 'task_items', ['candidate_id'], unique=False)
    op.create_index('ix_task_items_candidate_status', 'task_items', ['candidate_id', 'status'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'READY', 'FAILED', 'DELETED', name='file_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_candidate_id', 'uploaded_files', ['candidate_id'], unique=False)
    op.create_index('ix_uploaded_files_status', 'uploaded_files', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_thread_created', 'chat_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_thread_id', 'chat_messages', ['thread_id'], unique=False)
    op.create_table('essay_reviews',
    sa.Column('essay_draft_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_type', sa.Enum('AI', 'HUMAN', name='reviewer_type'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essay_draft_id'], ['essay_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_essay_reviews_essay_draft_id', 'essay_reviews', ['essay_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_essay_reviews_essay_draft_id', table_name='essay_reviews')
    op.drop_table('essay_reviews')
    op.drop_index('ix_chat_messages_thread_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_thread_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_uploaded_files_status', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_candidate_id', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_task_items_candidate_status', table_name='task_items')
    op.drop_index('ix_task_items_candidate_id', table_name='task_items')
    op.drop_table('task_items')
    op.drop_index('ix_strategy_decisions_type', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_candidate_id', table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index('ix_essay_drafts_candidate_id', table_name='essay_drafts')
    op.drop_table('essay_drafts')
    op.drop_index('ix_chat_threads_candidate_id', table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_table('candidate_profiles')
    op.drop_index('ix_ai_runs_status', table_name='ai_runs')
    op.drop_index('ix_ai_runs_run_type', table_name='ai_runs')
    op.drop_index('ix_ai_runs_candidate_id', table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index('ix_candidates_status', table_name='candidates')
    op.drop_index('ix_candidates_program_type', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
