"""add_users_user_sessions_refactor_candidates_admins

Revision ID: c041aced2d1e
Revises: 0ac80b149312
Create Date: 2026-03-22 18:36:35.249477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c041aced2d1e'
down_revision: Union[str, Sequence[str], None] = '0ac80b149312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
