"""add_completeness_score_to_candidate_profiles

Revision ID: cc961c750d3d
Revises: f93c04aedb80
Create Date: 2026-03-21 13:19:46.489222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc961c750d3d'
down_revision: Union[str, Sequence[str], None] = 'f93c04aedb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('completeness_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'completeness_score')
    # ### end Alembic commands ###
