"""add knowledge_chunks table

Revision ID: dd84a02d52ef
Revises: e1a2b3c4d5e6
Create Date: 2026-04-02 20:02:30.229243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd84a02d52ef'
down_revision: Union[str, Sequence[str], None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('source_key', sa.String(length=512), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('school', sa.String(length=512), nullable=True),
    sa.Column('program_slug', sa.String(length=128), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'chunk_index', name='uq_knowledge_chunks_source_chunk_idx')
    )
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_chunks_school_program_slug', 'knowledge_chunks', ['school', 'program_slug'], unique=False)
    op.create_index('ix_knowledge_chunks_source_key', 'knowledge_chunks', ['source_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_source_key', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_school_program_slug', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
