"""add_profile_complete_to_candidate_profiles

Revision ID: f93c04aedb80
Revises: c3b675f8bd21
Create Date: 2026-03-21 12:29:34.872673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93c04aedb80'
down_revision: Union[str, Sequence[str], None] = 'c3b675f8bd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('profile_complete', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'profile_complete')
    # ### end Alembic commands ###
